import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { ArticleBreadcrumbs } from "@/components/article-breadcrumbs";
import { BookbeatAd } from "@/components/bookbeat-ad";
import { StickyLeftAdRail } from "@/components/sticky-left-ad-rail";
import { FreightMinimumWageChart } from "@/components/freight-minimum-wage-chart";
import { freightMinimumWage as current, freightMinimumWageProposal as proposal, freightTariff2026 as tariff, freightSources as sources, freightMinimumWageHistory, freightScopeHistory, getFreightHistoryPeriods, freightFaq as faq, formatFreightRate as formatRate } from "@/lib/freight-minimum-wage";
import { getOccupationDetailViewModelBySlug } from "@/lib/occupation-detail-view-models";
import { getAbsoluteUrl, siteConfig } from "@/lib/site-config";

const pagePath = "/minstelonn/minstelonn-godstransport";
const title = "Minstelønn godstransport 2026 – lastebil og varebil";
const description = "Se gjeldende minstelønn for godstransport på vei. Satser for lastebil og varebil, flerdagsturer, diett, overtid og historisk utvikling.";
const image = "/images/minimum-wage/godstransport-hero.png";
export const metadata: Metadata = {
  title, description, alternates: { canonical: pagePath },
  openGraph: { type: "website", locale: "nb_NO", url: pagePath, siteName: siteConfig.name, title, description, images: [{ url: image, alt: "Lastebil ved en norsk godsterminal" }] },
  twitter: { card: "summary_large_image", title, description, images: [image] },
};
const sections = [["virkeomrade", "Hvem har krav på minstelønn?"], ["varebil", "Minstelønn for varebilsjåfører"], ["flerdagsturer", "Lønn på flerdagsturer"], ["tariff", "Lovpålagt minstelønn eller tariff?"], ["historikk", "Historiske satser"], ["faktisk-lonn", "Hva tjener lastebilsjåfører?"], ["faq", "Ofte stilte spørsmål"], ["kilder", "Kilder og metode"]] as const;
const relatedOccupations = [
  { label: "Lastebil- og trailersjåfører", href: "/yrke/lastebil-og-trailersjaforer-lonn" },
  { label: "Bil-, drosje- og varebilførere", href: "/yrke/bil-drosje-og-varebilforere-lonn" },
] as const;
const salaryTools = [
  { href: "/yrker", label: "Alle yrker", description: "Utforsk lønnstall for hundrevis av yrker" },
  { href: "/lonnsjekk", label: "Lønnsjekk", description: "Sammenlign lønnen din med relevant statistikk" },
  { href: "/jobbtilbud", label: "Lønnstilbud", description: "Vurder lønnen i et nytt jobbtilbud" },
  { href: "/lonnskalkulator", label: "Lønnskalkulator", description: "Regn om mellom års-, måneds- og timelønn" },
] as const;


const recommendedArticles = [
  { href: "/blogg/5-ting-du-bor-ha-klart-for-lonnssamtalen", label: "5 ting du bør ha klart før lønnssamtalen", category: "Lønnsforhandling" },
  { href: "/blogg/7-gode-argumenter-for-a-be-om-hoyere-lonn", label: "7 gode argumenter for å be om høyere lønn", category: "Lønnsforhandling" },
] as const;

export default async function FreightMinimumWagePage() {
  const [truckModel, vanModel] = await Promise.all([
    getOccupationDetailViewModelBySlug("lastebil-og-trailersjaforer-lonn"),
    getOccupationDetailViewModelBySlug("bil-drosje-og-varebilforere-lonn"),
  ]);
  const truckSalary = truckModel?.data.distribution;
  const vanSalary = vanModel?.data.distribution;
  const scopeEvent = freightScopeHistory.find((event) => event.event === "scope-change")!;
  const history = getFreightHistoryPeriods();
  const structuredData = [
    { "@context": "https://schema.org", "@type": "WebPage", name: title, description, url: getAbsoluteUrl(pagePath), inLanguage: "nb-NO", dateModified: current.verifiedAt },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Hjem", item: getAbsoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "Minstelønn", item: getAbsoluteUrl("/minstelonn") }, { "@type": "ListItem", position: 3, name: "Godstransport", item: getAbsoluteUrl(pagePath) }] },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
  ];
  return <main className="min-h-screen bg-white px-4 pb-16 pt-5 sm:px-6 lg:px-8">
    {structuredData.map((data, index) => <script dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} key={index} type="application/ld+json" />)}
    <div className="relative mx-auto max-w-7xl">
      <StickyLeftAdRail />
      <ArticleBreadcrumbs href="/minstelonn" section="Minstelønn" title="Godstransport" />
      <div className="relative mx-auto mt-7 max-w-[1080px] overflow-hidden rounded-[28px] bg-[radial-gradient(circle_at_70%_25%,#f3ead4_0%,#fbfdf9_38%,#e8f3e9_100%)] px-5 pb-8 pt-8 sm:px-10 lg:min-h-[410px] lg:px-[250px] lg:pb-10 lg:pt-10">
        <div aria-hidden="true" className="absolute -left-20 bottom-[-95px] size-72 rounded-full bg-[#b9d6ae]/50" /><div aria-hidden="true" className="absolute -right-12 top-4 size-56 rounded-[45%] bg-[#e4cf91]/35" />
        <div className="absolute right-8 top-8 hidden h-[330px] w-[220px] overflow-hidden rounded-[46%_46%_18%_46%] lg:block"><Image alt="Lastebil ved en lys godsterminal, med en varebil i bakgrunnen" className="h-full w-full object-cover object-[52%_58%]" fill priority sizes="220px" src="/images/minimum-wage/godstransport-hero.png" /></div>
        <header className="relative z-10 mx-auto max-w-3xl text-center">
          <p className="inline-flex rounded-full bg-[#e4f2e7] px-5 py-2 text-xs font-bold uppercase tracking-[0.17em] text-[#15533d]">Godstransport</p>
          <h1 className="mx-auto mt-6 text-[clamp(2.45rem,5vw,4.8rem)] font-[760] leading-[1.03] tracking-[-0.035em] text-[#101820]">Minstelønn for godstransport på vei</h1>
          <p className="mx-auto mt-5 max-w-[690px] text-base leading-[1.65] text-[#3f4a45] sm:text-[1.12rem]">Sjåfører som utfører godstransport på vei med kjøretøy med tillatt totalvekt over 2,5 tonn, skal som hovedregel ha minst <strong>{formatRate(current.hourlyRate)} per time</strong>. Her finner du gjeldende minstelønn, regler for varebiler, flerdagsturer, diett og overtid, og historiske satser tilbake til 2016.</p>
          <div className="mx-auto mt-7 grid max-w-[650px] gap-3 text-sm text-[#52627d] sm:grid-cols-3"><p><strong className="block text-[#15533d]">Gjeldende fra</strong>{formatDate(current.effectiveFrom)}</p><p><strong className="block text-[#15533d]">Lovpålagt timelønn</strong>{formatRate(current.hourlyRate)}/time</p><p><strong className="block text-[#15533d]">Sist kontrollert</strong>{formatDate(current.verifiedAt)}</p></div>
        </header>
        <div className="relative z-10 mx-auto mt-6 h-44 w-full max-w-sm overflow-hidden rounded-[28px] sm:h-52 lg:hidden"><Image alt="Lastebil ved en lys godsterminal, med en varebil i bakgrunnen" className="h-full w-full object-cover object-[50%_60%]" fill priority sizes="(max-width: 1024px) 384px, 0px" src="/images/minimum-wage/godstransport-hero.png" /></div>
      </div>



      <div className="mx-auto mt-9 grid max-w-[1000px] gap-4 sm:grid-cols-3">
        <article className="rounded-[11px] border border-[#15533d] bg-[linear-gradient(135deg,#1d634c,#104733)] px-5 py-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.12em]">Lovpålagt timelønn</p><p className="mt-3 text-4xl font-bold tabular-nums tracking-[-0.05em]">{formatRate(current.hourlyRate)}</p><p className="mt-3 text-xs leading-5 text-white/80">Gjeldende fra {formatDate(current.effectiveFrom)}. Én sats uten egne trinn for alder, fagbrev eller ansiennitet.</p></article>
        <article className="rounded-[11px] border border-[#d8eadf] bg-[#f3faf5] px-5 py-6 text-[#19243b]"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#15533d]">Tillatt totalvekt</p><p className="mt-3 text-3xl font-bold">Over 2,5 tonn</p><p className="mt-3 text-xs leading-5 text-[#52627d]">Varebiltransport ble omfattet fra 1. juni 2025. Egentransport er unntatt.</p></article>
        <article className="rounded-[11px] border border-[#d8eadf] bg-[#f3faf5] px-5 py-6 text-[#19243b]"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#15533d]">Flerdagsturer</p><p className="mt-3 text-3xl font-bold">Minst 7,5 timer</p><p className="mt-3 text-xs leading-5 text-[#52627d]">Betalt per døgn mellom oppstarts- og avslutningsdøgnet. Diett kommer separat.</p></article>
      </div>
      <aside className="mx-auto mt-7 max-w-[920px] rounded-[11px] border border-amber-700/25 bg-amber-50 p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.14em] text-amber-800">Under behandling · 2026</p><h2 className="mt-2 text-xl font-semibold text-slate-950">Ny minstelønn foreslått: {formatRate(proposal.hourlyRate)} per time</h2><p className="mt-2 text-sm leading-6 text-slate-700">Tariffnemnda behandler fortsatt saken. Forslaget er ikke vedtatt, og har ingen fastsatt ikrafttredelsesdato. Dagens lovpålagte sats er fortsatt <strong>{formatRate(current.hourlyRate)} per time</strong>. {formatRate(tariff.lowestHourlyRate)} er allerede laveste nye tariffsats i Godsoverenskomsten fra 1. august 2026.</p><p className="mt-3 text-xs font-semibold text-amber-900">Sist kontrollert: {formatDate(current.verifiedAt)}.</p><SourceLine href={sources.proposal} label="Tariffnemnda – pågående sak" /></aside>
      <BookbeatAd className="mx-auto mt-8 max-w-[920px]" placement="overview-between-sections" />
      <div className="mx-auto mt-7 max-w-[920px]"><FreightMinimumWageChart endDate={current.verifiedAt} points={freightMinimumWageHistory} scopeEventDate={scopeEvent.effectiveFrom} /></div>
      <nav aria-labelledby="innhold" className="mx-auto mt-7 max-w-[920px] rounded-[11px] border border-slate-200 bg-slate-50 p-5 sm:px-7"><h2 className="text-xl font-bold text-slate-950" id="innhold">Innhold på siden</h2><ol className="mt-3 grid sm:grid-cols-2">{sections.map(([id, label], index) => <li key={id}><a className="grid grid-cols-[2rem_1fr] rounded-[7px] px-2 py-1.5 text-slate-800 hover:bg-white hover:text-[#15533d]" href={"#" + id}><span className="text-xs text-slate-400">{String(index + 1).padStart(2, "0")}</span><span className="font-medium">{label}</span></a></li>)}</ol></nav>
      <div className="mx-auto mt-8 max-w-[920px] min-w-0">
        <Section id="virkeomrade" title="Hvem har krav på minstelønn for godstransport?"><p>Forskriften gjelder ansatte som utfører godstransport på vei med kjøretøy med tillatt totalvekt over 2,5 tonn. Dette kan være lastebilsjåfører, trailersjåfører, distribusjonssjåfører, langtransportsjåfører, godssjåfører og enkelte varebilsjåfører.</p><InfoGrid items={[["Lastebil og trailer", "Lokal, nasjonal og langtransport kan omfattes når øvrige vilkår er oppfylt."], ["Varebil over 2,5 tonn", "Varebilsegmentet kom inn i virkeområdet 1. juni 2025."], ["Én lovpålagt timesats", "Ingen egen høyere lovsats for fagbrev, lang ansiennitet eller trailer fremfor lastebil."]]} /><p>Det er arbeidet og virkeområdet som avgjør. Yrkestittelen og SSB-koden alene er ikke nok. Lærlinger, personer på arbeidsmarkedstiltak og transport av virksomhetens egne varer er unntatt.</p><div className="rounded-[9px] border border-slate-200 bg-slate-50 p-5 sm:p-6"><h3 className="font-bold text-slate-950">Se lønn for relevante yrker</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{relatedOccupations.map((occupation) => <li className="flex items-start gap-2 text-sm leading-6" key={occupation.href}><span aria-hidden="true" className="mt-2 size-1.5 shrink-0 rounded-full bg-[#15533d]" /><Link className="font-semibold text-[#15533d] hover:underline" href={occupation.href}>{occupation.label}</Link></li>)}</ul><p className="mt-3 text-xs leading-5 text-slate-500">SSB-gruppen for bil-, drosje- og varebilførere inkluderer også persontransport og kjøretøy som ikke omfattes.</p></div><SourceLine href={sources.regulation} label="Forskriften § 2" /></Section>
        <Section id="varebil" title="Minstelønn for varebilsjåfører"><p>Fra 1. juni 2025 gjelder forskriften også godstransport med kjøretøy med tillatt totalvekt mellom 2,5 og 3,5 tonn. Før dette var grensen over 3,5 tonn. Det er <strong>tillatt totalvekt</strong> som er relevant, ikke hvor mye bilen er lastet med på den enkelte turen.</p><div className="grid gap-4 sm:grid-cols-2"><InfoCard title="Over 2 500 kg">Godstransporten kan omfattes, og gjeldende sats er {formatRate(current.hourlyRate)} per time. Egentransport og øvrige unntak må vurderes.</InfoCard><InfoCard title="2 500 kg eller lettere">Denne allmenngjøringsforskriften gir ingen minstesats for kjøretøy på nøyaktig 2,5 tonn eller lettere. Arbeidsavtale eller tariffavtale kan likevel gi krav på bestemt lønn.</InfoCard></div><DataTable headers={["Periode", "Timesats", "Vektgrense"]} rows={[["01.11.2024–31.05.2025", "222,00 kr", "Over 3,5 tonn"], ["01.06.2025–14.06.2025", "222,00 kr", "Over 2,5 tonn"], ["Fra 15.06.2025", formatRate(current.hourlyRate), "Over 2,5 tonn"]]} /><SourceLine href={sources.regulation} label="Forskriften §§ 2 og 8" /></Section>
        <Section id="flerdagsturer" title="Lønn på flerdagsturer: minst 7,5 timer per mellomliggende døgn"><p>Ingen døgn på flerdagsturer, med unntak av oppstarts- og avslutningsdøgn, skal lønnes med mindre enn {current.multiDayTrip.minimumPaidHoursPerFullIntermediateDay.toLocaleString("nb-NO")} timer per døgn. Dette er et allmenngjort lønnsvilkår.</p><DataTable headers={["Tur mandag–torsdag", "7,5-timersgarantien"]} rows={[["Mandag – oppstartsdøgn", "Særregelen gjelder ikke"], ["Tirsdag", "Minst 7,5 betalte timer"], ["Onsdag", "Minst 7,5 betalte timer"], ["Torsdag – avslutningsdøgn", "Særregelen gjelder ikke"]]} /><InfoCard title="Første og siste døgn skal også vurderes">Unntaket betyr ikke at første og siste døgn kan være ulønnet. Det betyr bare at den særskilte garantien på minst 7,5 timer ikke gjelder disse døgnene.</InfoCard><p>Med ordinær timelønn lik minstesatsen tilsvarer 7,5 timer <strong>{formatRate(current.hourlyRate * 7.5)}</strong>. Mer betalt arbeidstid og eventuelle tillegg kommer i tillegg etter reglene som gjelder.</p><SourceLine href={sources.regulation} label="Forskriften § 3" /></Section>
        <BookbeatAd className="my-8 sm:my-10" placement="minimum-wage-mid-content" />
        <Section id="tariff" title="229 eller 244,50 kroner: minstelønn, tariff og faktisk lønn"><p>Dagens lovpålagte sats er {formatRate(current.hourlyRate)} per time. Den gjelder uten egne trinn for fagbrev eller ansiennitet. Godsoverenskomsten har derimot ansiennitetstrinn, fagbrevtillegg og andre tariffvilkår.</p><DataTable headers={["Talltype", "Nivå", "Hva betyr det?"]} rows={[["Lovpålagt minstelønn", formatRate(current.hourlyRate) + "/time", "Gjeldende allmenngjort lønnsgulv"], ["Laveste tariffsats", formatRate(tariff.lowestHourlyRate) + "/time", "Godsoverenskomsten fra 1. august 2026"], ["Foreslått allmenngjort sats", formatRate(proposal.hourlyRate) + "/time", "Under behandling – ingen vedtatt dato"], ...(truckSalary?.total?.median != null ? [["Faktisk lønnsstatistikk", formatRate(truckSalary.total.median) + "/måned", "Median for lastebil- og trailersjåfører i " + truckSalary.periodLabel]] : [])]} /><h3 className="text-xl font-bold text-slate-950">Godsoverenskomsten før 2026-oppgjøret</h3><p>Fra 1. juni 2024 var tariffsatsene 222,00 kr ved 0–3 års ansiennitet, 224,00 kr ved 3–6 år og 226,00 kr ved minst seks år. Fagbrevtillegget var 13,00 kr. Mellomoppgjøret i 2025 løftet laveste tariffnivå til 229,00 kr.</p><h3 className="text-xl font-bold text-slate-950">Godkjent tariffoppgjør i 2026</h3><p>Fra 1. april ble det avtalt {formatRate(tariff.generalIncrease)} i generelt tillegg og {formatRate(tariff.freightIncrease)} i godstillegg per time. Fagbrevtillegget økte til {formatRate(tariff.skilledSupplement)}. Fra 1. august økte minstesatsen ytterligere med {formatRate(tariff.additionalMinimumIncrease)}, slik at laveste tariffnivå ble {formatRate(tariff.lowestHourlyRate)}.</p><p>YTF kunngjorde at oppgjøret var vedtatt etter uravstemning 1. juli 2026. Tariffendringen er ikke automatisk en endring av allmenngjøringsforskriften. Ansiennitet og fagbrev kan gi høyere tariffnivå enn den laveste satsen.</p><SourceLine href={sources.tariff2024} label="Godsoverenskomsten 2024–2026" /><SourceLine href={sources.tariff} label="Fellesforbundet – tariffoppgjøret 2026" /><SourceLine href={sources.tariffApproved} label="YTF – godsoppgjøret er vedtatt" /></Section>
        <Section id="historikk" title="Historiske lovpålagte minstelønnssatser"><p>Den første allmenngjøringen trådte i kraft 1. juli 2015 med 158,32 kroner per time. Samme sats gjaldt gjennom 2016. Grafen før innholdsfortegnelsen viser faktiske satsendringer fra 2016; tabellen viser også da vektgrensen ble endret uten at lønnen steg.</p><DataTable minWidth="680px" headers={["Gyldig periode", "Lovpålagt per time", "Hovedvirkeområde"]} rows={history.map((point) => [point.effectiveFrom === "2015-07-01" ? "2016–31.05.2017" : formatShortDate(point.effectiveFrom) + (point.effectiveTo ? "–" + formatShortDate(point.effectiveTo) : "–nå"), formatRate(point.hourlyRate), "Over " + (point.vehicleWeightOverKg / 1000).toLocaleString("nb-NO") + " tonn"])} /><p>Fra 158,32 kroner i 2016 til 229,00 kroner er økningen 70,68 kroner per time, omtrent 44,6 prosent nominelt. Det er ikke justert for prisvekst.</p><InfoCard title="Historikken bruker faktisk gjeldende satser">Den opprinnelig fastsatte 2017-satsen på 165,65 kr ble endret til 167,65 kr før ikrafttredelsen og er ikke tatt med som en gjeldende sats. For 2018 brukes Tariffnemndas opprinnelige vedtak på 171,45 kr; en senere konsolidert forskrift kan vise 2019-satsen.</InfoCard><p>7,5-timersregelen ble allmenngjort fra 15. desember 2022. Historiske timesatser innebærer ikke at alle dagens øvrige vilkår gjaldt i hele perioden. Eldre forskrifter hadde også andre avgrensninger for internasjonal transport.</p><SourceLine href={sources.original2018} label="Tariffnemnda – opprinnelig vedtak 2018" /></Section>
        <Section id="faktisk-lonn" title="Hva tjener lastebilsjåfører faktisk?"><p>Minstelønnen er et gulv, ikke vanlig lønn i yrket. SSB-tabell 11418 viser månedslønn omregnet til heltidsekvivalenter. Tallene her gjelder begge kjønn, alle sektorer og heltid og deltid samlet.</p>{truckSalary && <><h3 className="text-xl font-bold text-slate-950">Lastebil- og trailersjåfører · SSB 8332 · {truckSalary.periodLabel}</h3><div className="grid gap-4 sm:grid-cols-2">{truckSalary.total?.average != null && <Comparison label="Gjennomsnittlig månedslønn" rate={truckSalary.total.average} />}{truckSalary.total?.median != null && <Comparison label="Median månedslønn" rate={truckSalary.total.median} />}</div></>}<p>Dette er faktisk lønnsstatistikk, og kan ikke leses som en lovpålagt timesats. Se mer på <Link className="font-semibold text-[#15533d] hover:underline" href="/yrke/lastebil-og-trailersjaforer-lonn">yrkessiden for lastebil- og trailersjåfører</Link>.</p>{vanSalary && <InfoCard title={"Bil-, drosje- og varebilførere · SSB 8322 · " + vanSalary.periodLabel}>Gjennomsnitt: {vanSalary.total?.average != null ? formatRate(vanSalary.total.average) : "Ikke tilgjengelig"} per måned. Median: {vanSalary.total?.median != null ? formatRate(vanSalary.total.median) : "Ikke tilgjengelig"}. Gruppen inkluderer også persontransport og varebiler som ikke omfattes av minstelønnsforskriften.</InfoCard>}<SourceLine href={sources.ssb} label="SSB tabell 11418 – lønnsstatistikk" /></Section>
        <BookbeatAd className="my-8 sm:my-10" placement="minimum-wage-before-faq" />
        <Section id="faq" title="Ofte stilte spørsmål"><div className="divide-y divide-slate-200 overflow-hidden rounded-[5px] border border-black/10 bg-white">{faq.map((item) => <details className="group px-5 py-4 open:bg-[#fbfbf8]" key={item.question}><summary className="cursor-pointer list-none pr-8 font-semibold text-slate-950 marker:hidden">{item.question}<span aria-hidden="true" className="float-right text-[#15533d] group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{item.answer}</p></details>)}</div></Section>
        <Section id="kilder" title="Kilder og metode"><p>Sats og virkeområde er kontrollert {formatDate(current.verifiedAt)} mot Arbeidstilsynet, gjeldende forskrift og Tariffnemndas pågående sak. Lovpålagt sats, tariffoppgjør og forslag lagres separat. Virkeområdeendringen 1. juni 2025 er en egen hendelse og gir ikke et ekstra lønnspunkt i grafen.</p><p>SSB-tallene leses fra prosjektets eksisterende yrkesdata for tabell 11418, oppdatert 28. august 2026. Historiske forskrifter og opprinnelige vedtak brukes til å skille faktisk ikrafttredelse fra senere konsoliderte satser.</p><ul className="space-y-2 text-sm font-semibold text-[#15533d]">{[[sources.rates, "Arbeidstilsynet – minstelønn"], [sources.regulation, "Lovdata – gjeldende forskrift FOR-2024-10-29-2601"], [sources.regulationText, "Arbeidstilsynet – gjeldende forskriftstekst"], [sources.amendment, "Lovdata – satsendring fra 15. juni 2025"], [sources.proposal, "Tariffnemnda – fortsatt allmenngjøring i 2026"], [sources.tariff, "Fellesforbundet – tariffoppgjøret 2026"], [sources.tariffApproved, "YTF – oppgjøret vedtatt"], [sources.tariff2024, "Godsoverenskomsten 2024–2026"], [sources.firstRegulation, "Lovdata – første allmenngjøring i 2015"], [sources.regulation2017, "Lovdata – gjeldende sats fra juni 2017"], [sources.original2018, "Tariffnemnda – opprinnelig vedtak fra 2018"], [sources.regulation2018, "Lovdata – 2018-forskriften, senere endret i 2019"], [sources.amendment2019, "Lovdata – satsendring fra 1. juli 2019"], [sources.regulation2021, "Tariffnemnda – vedtak fra 2021"], [sources.regulation2022, "Lovdata – forskriften fra 2022, senere endret i 2023"], [sources.original2022, "Tariffnemnda – opprinnelig vedtak fra 2022"], [sources.original2024, "Tariffnemnda – vedtak fra 2024"], [sources.postedDrivers, "Arbeidstilsynet – utsendte sjåfører"], [sources.overtime, "Arbeidstilsynet – overtid"], [sources.ssb, "SSB – tabell 11418"]].map(([href, label]) => <li key={href}><a className="hover:underline" href={href}>{label} ↗</a></li>)}</ul></Section>
<section aria-labelledby="videre-title" className="mt-14 overflow-hidden rounded-[18px] border border-[#cfded6] bg-[#f7faf8] shadow-[0_18px_50px_rgba(15,23,42,0.06)]">
            <div className="border-b border-[#dce7e1] bg-white px-5 py-6 sm:px-8 sm:py-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--primary)]">Utforsk videre</p><h2 className="mt-2 text-[1.75rem] font-bold leading-[1.15] tracking-[-0.03em] text-slate-950 sm:text-[2.1rem]" id="videre-title">Fra minstelønn til faktisk sjåførlønn</h2><p className="mt-3 max-w-3xl text-base leading-7 text-slate-700">Minstelønn er et lovpålagt gulv, ikke det samme som vanlig lønn i yrket. Bruk lønnsverktøyene eller les mer om sjåførlønn og lønnsforhandling.</p><Link className="mt-5 inline-flex items-center gap-2 rounded-[8px] bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[var(--primary-strong)]" href="/yrke/lastebil-og-trailersjaforer-lonn">Se hva lastebil- og trailersjåfører faktisk tjener <span aria-hidden="true">→</span></Link></div>
            <div className="grid gap-8 px-5 py-6 sm:px-8 sm:py-8 lg:grid-cols-2"><div><h3 className="text-lg font-bold text-slate-950">Nyttige lønnsverktøy</h3><div className="mt-4 grid gap-2">{salaryTools.map((item) => <Link className="group flex items-center justify-between gap-4 rounded-[10px] border border-slate-200 bg-white px-4 py-3 transition hover:border-[#9fc5b5] hover:shadow-sm" href={item.href} key={item.href}><span><strong className="block text-sm text-slate-950 group-hover:text-[var(--primary)]">{item.label}</strong><span className="mt-0.5 block text-xs leading-5 text-slate-500">{item.description}</span></span><span aria-hidden="true" className="shrink-0 text-lg text-[var(--primary)]">→</span></Link>)}</div></div><div><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-lg font-bold text-slate-950">Anbefalte artikler</h3><Link className="text-xs font-semibold text-[var(--primary)] hover:underline" href="/blogg/kategori/lonnsforhandling">Alle om lønnsforhandling →</Link></div><div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{recommendedArticles.map((article) => <Link className="group flex items-start justify-between gap-4 py-3.5" href={article.href} key={article.href}><span><span className="block text-[11px] font-bold uppercase tracking-[0.1em] text-slate-500">{article.category}</span><strong className="mt-1 block text-sm leading-5 text-slate-950 group-hover:text-[var(--primary)] group-hover:underline">{article.label}</strong></span><span aria-hidden="true" className="mt-3 shrink-0 text-lg text-[var(--primary)]">→</span></Link>)}</div></div></div>
          </section>
      </div>
    </div>
  </main>;
}
function Section({ children, id, title }: { children: ReactNode; id: string; title: string }) { return <section className="scroll-mt-6 space-y-6 py-10 first:pt-0 [&>p]:max-w-3xl [&>p]:text-[1.03rem] [&>p]:leading-[1.8] [&>p]:text-slate-950 sm:[&>p]:text-lg" id={id}><h2 className="text-balance text-[1.75rem] font-bold leading-[1.15] tracking-[-0.03em] text-slate-950 sm:text-[2.1rem]">{title}</h2>{children}</section>; }
function InfoCard({ children, title }: { children: ReactNode; title: string }) { return <article className="rounded-[8px] border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{children}</p></article>; }
function InfoGrid({ items }: { items: readonly (readonly [string, string])[] }) { return <div className="grid gap-4 md:grid-cols-3">{items.map(([heading, text]) => <InfoCard key={heading} title={heading}>{text}</InfoCard>)}</div>; }
function Comparison({ label, rate }: { label: string; rate: number }) { return <article className="rounded-[9px] border border-[#d8eadf] bg-[#f3faf5] p-5"><p className="font-semibold text-slate-950">{label}</p><p className="mt-3 text-3xl font-bold tabular-nums text-[#15533d]">{formatRate(rate)}<span className="ml-2 text-sm font-medium text-slate-500">/måned</span></p></article>; }
function SourceLine({ href, label }: { href: string; label: string }) { return <p className="text-xs leading-5 text-slate-500">Kilde: <a className="font-semibold text-[#15533d] hover:underline" href={href}>{label} ↗</a></p>; }
function DataTable({ headers, minWidth = "620px", rows }: { headers: string[]; minWidth?: string; rows: ReactNode[][] }) { return <div className="overflow-x-auto rounded-[5px] border border-black/10 bg-white"><table className="w-full border-collapse text-left" style={{ minWidth }}><thead className="bg-[#f1f7f2] text-sm text-slate-700"><tr>{headers.map((header) => <th className="px-4 py-3 font-semibold" key={header}>{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-200 text-sm text-slate-800">{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td className="px-4 py-3.5" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }

function formatDate(value: string) { return new Intl.DateTimeFormat("nb-NO", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }

function formatShortDate(value: string) { return new Intl.DateTimeFormat("nb-NO", { day: "2-digit", month: "2-digit", year: "numeric", timeZone: "UTC" }).format(new Date(value + "T00:00:00Z")); }
