import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { ArticleBreadcrumbs } from "@/components/article-breadcrumbs";
import { BookbeatAd } from "@/components/bookbeat-ad";
import { StickyLeftAdRail } from "@/components/sticky-left-ad-rail";
import { AutomotiveTariffChart } from "@/components/automotive-tariff-chart";
import { automotiveCategories, automotiveMinimumWage as current, automotiveMinimumWageProposal as proposal, automotiveSources as sources, biloverenskomstenTariffHistory, formatAutomotiveRate as formatRate } from "@/lib/automotive-minimum-wage";
import { automotiveFaq as faq } from "@/lib/automotive-minimum-wage-faq";
import salaryData from "@/content/blog/data/bilmekaniker-lonn-2025.json";
import { getAbsoluteUrl, siteConfig } from "@/lib/site-config";

const pagePath = "/minstelonn/minstelonn-bilbransjen";
const title = "Minstelønn bilbransjen 2026 – bilmekaniker og bilpleie";
const description = "Se gjeldende minstelønn i bilbransjen for fagarbeidere og hjelpearbeidere. Satser for bilmekanikere, bilpleie, dekkskift og historisk tariffutvikling.";
const image = "/images/minimum-wage/bilbransjen-hero.png";
export const metadata: Metadata = {
  title, description, alternates: { canonical: pagePath },
  openGraph: { type: "website", locale: "nb_NO", url: pagePath, siteName: siteConfig.name, title, description, images: [{ url: image, alt: "Verktøy og arbeidstøy i bilverksted" }] },
  twitter: { card: "summary_large_image", title, description, images: [image] },
};
const sections = [["virkeomrade", "Hvem omfattes?"], ["fagarbeider", "Fagarbeider eller hjelpearbeider"], ["praksis", "Ett års praksis"], ["bilpleie", "Bilpleie, bilvask og dekk"], ["unntak", "Viktige unntak"], ["arbeidstoy", "Arbeidstøy og vernesko"], ["overtid", "Overtid og arbeidstid"], ["tariff", "Lov og tariff"], ["tillegg", "Kveld, natt og smusstillegg"], ["historikk", "Historisk tariffutvikling"], ["faktisk-lonn", "Hva tjener bilmekanikere?"], ["faq", "Ofte stilte spørsmål"], ["kilder", "Kilder og metode"]] as const;

const relatedOccupations = [
  {
    "label": "Bilmekanikere",
    "href": "/yrke/bilmekanikere-lonn"
  },
  {
    "label": "Overflatebehandlere og lakkerere",
    "href": "/yrke/overflatebehandlere-og-lakkerere-lonn"
  },
  {
    "label": "Bilvaskere",
    "href": "/yrke/bilvaskere-lonn"
  }
] as const;

const salaryTools = [
  { href: "/yrker", label: "Alle yrker", description: "Utforsk lønnstall for hundrevis av yrker" },
  { href: "/lonnsjekk", label: "Lønnsjekk", description: "Sammenlign lønnen din med relevant statistikk" },
  { href: "/jobbtilbud", label: "Lønnstilbud", description: "Vurder lønnen i et nytt jobbtilbud" },
  { href: "/lonnskalkulator", label: "Lønnskalkulator", description: "Regn om mellom års-, måneds- og timelønn" },
] as const;

const recommendedArticles = [
  { href: "/blogg/lonn-alder-og-kjonnsforskjeller-blant-bilmekanikere", label: "Lønn, alder og kjønnsforskjeller blant bilmekanikere", category: "Bilmekanikerlønn" },
  { href: "/blogg/5-ting-du-bor-ha-klart-for-lonnssamtalen", label: "5 ting du bør ha klart før lønnssamtalen", category: "Lønnsforhandling" },
  { href: "/blogg/7-gode-argumenter-for-a-be-om-hoyere-lonn", label: "7 gode argumenter for å be om høyere lønn", category: "Lønnsforhandling" },
] as const;

export default function AutomotiveMinimumWagePage() {
  const salary = salaryData.rows.find((row) => row.code === "7231")!;
  const tariff = biloverenskomstenTariffHistory.at(-1)!;
  const structuredData = [
    { "@context": "https://schema.org", "@type": "WebPage", name: title, description, url: getAbsoluteUrl(pagePath), inLanguage: "nb-NO", dateModified: current.verifiedAt },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Hjem", item: getAbsoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "Minstelønn", item: getAbsoluteUrl("/minstelonn") }, { "@type": "ListItem", position: 3, name: "Bilbransjen", item: getAbsoluteUrl(pagePath) }] },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
  ];
  return <main className="min-h-screen bg-white px-4 pb-16 pt-5 sm:px-6 lg:px-8">
    {structuredData.map((data, index) => <script dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} key={index} type="application/ld+json" />)}
    <div className="relative mx-auto max-w-7xl">
      <StickyLeftAdRail />
      <ArticleBreadcrumbs href="/minstelonn" section="Minstelønn" title="Bilbransjen" />
      <div className="relative mx-auto mt-7 max-w-[1080px] overflow-hidden rounded-[28px] bg-[radial-gradient(circle_at_70%_25%,#f3ead4_0%,#fbfdf9_38%,#e8f3e9_100%)] px-5 pb-8 pt-8 sm:px-10 lg:min-h-[410px] lg:px-[250px] lg:pb-10 lg:pt-10">
        <div aria-hidden="true" className="absolute -left-20 bottom-[-95px] size-72 rounded-full bg-[#b9d6ae]/50" /><div aria-hidden="true" className="absolute -right-12 top-4 size-56 rounded-[45%] bg-[#e4cf91]/35" />
        <div className="absolute right-8 top-8 hidden h-[330px] w-[220px] overflow-hidden rounded-[46%_46%_18%_46%] lg:block"><Image alt="Mekanikerhansker, arbeidstøy og verktøy på en benk i et lyst bilverksted" className="h-full w-full object-cover object-[52%_58%]" fill priority sizes="220px" src="/images/minimum-wage/bilbransjen-hero.png" /></div>
        <header className="relative z-10 mx-auto max-w-3xl text-center">
          <p className="inline-flex rounded-full bg-[#e4f2e7] px-5 py-2 text-xs font-bold uppercase tracking-[0.17em] text-[#15533d]">Bilbransjen</p>
          <h1 className="mx-auto mt-6 text-[clamp(2.45rem,5vw,4.8rem)] font-[760] leading-[1.03] tracking-[-0.035em] text-[#101820]">Minstelønn i bilbransjen</h1>
          <p className="mx-auto mt-5 max-w-[690px] text-base leading-[1.65] text-[#3f4a45] sm:text-[1.12rem]">Fra 15. juni 2026 har bilbransjen for første gang lovpålagt minstelønn. En nyutlært fagarbeider skal minst ha <strong>{formatRate(current.newlyQualifiedSkilled)} per time</strong>, mens en hjelpearbeider som har fylt 18 år skal ha minst {formatRate(current.helper18Plus)}. Her finner du gjeldende satser, hvem reglene gjelder for, tariffen og historisk utvikling.</p>
          <div className="mx-auto mt-7 grid max-w-[650px] gap-3 text-sm text-[#52627d] sm:grid-cols-3"><p><strong className="block text-[#15533d]">Gjeldende fra</strong>{formatDate(current.effectiveFrom)}</p><p><strong className="block text-[#15533d]">Nyutlært fagarbeider</strong>{formatRate(current.newlyQualifiedSkilled)}/time</p><p><strong className="block text-[#15533d]">Sist kontrollert</strong>{formatDate(current.verifiedAt)}</p></div>
        </header>
        <div className="relative z-10 mx-auto mt-6 h-44 w-full max-w-sm overflow-hidden rounded-[28px] sm:h-52 lg:hidden"><Image alt="Mekanikerhansker, arbeidstøy og verktøy på en benk i et lyst bilverksted" className="h-full w-full object-cover object-[50%_60%]" fill priority sizes="(max-width: 1024px) 384px, 0px" src="/images/minimum-wage/bilbransjen-hero.png" /></div>
      </div>


      <div className="mx-auto mt-9 max-w-[1000px]">
        <p className="mb-3 text-center text-xs font-bold uppercase tracking-[0.14em] text-[#15533d]">Lovpålagt fra 15. juni 2026</p>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{automotiveCategories.map((item, index) => <article className={index === 0 ? "rounded-[11px] border border-[#15533d] bg-[linear-gradient(135deg,#1d634c,#104733)] px-4 py-5 text-white" : "rounded-[11px] border border-[#d8eadf] bg-[#f3faf5] px-4 py-5 text-[#19243b]"} key={item.key}><p className="text-xs font-semibold">{item.label}</p><p className="mt-3 text-3xl font-bold tabular-nums tracking-[-0.05em]">{formatRate(current[item.key])}</p><p className="mt-3 text-xs">Per time · lovpålagt minstesats</p></article>)}</div>
        <SourceLine href={sources.rates} label="Arbeidstilsynet – gjeldende satser" />
      </div>
      <aside className="mx-auto mt-7 max-w-[920px] rounded-[11px] border border-amber-700/25 bg-amber-50 p-5 sm:p-7">
        <p className="text-xs font-bold uppercase tracking-[0.14em] text-amber-800">Under behandling · 2026</p><h2 className="mt-2 text-xl font-semibold text-slate-950">Ny minstelønn foreslått</h2>
        <p className="mt-2 text-sm leading-6 text-slate-700">Tariffnemnda vurderer å øke satsen for nyutlærte fagarbeidere fra {formatRate(current.newlyQualifiedSkilled)} til {formatRate(proposal.newlyQualifiedSkilled)} per time. Forslaget er ikke vedtatt. Dagens lovpålagte sats er fortsatt {formatRate(current.newlyQualifiedSkilled)}.</p>
        <p className="mt-3 text-sm leading-6 text-slate-700">De fire foreslåtte satsene er {automotiveCategories.map((item) => formatRate(proposal[item.key])).join(" / ")}, i samme rekkefølge som satskortene. Høringsfristen var 20. august 2026. Målet om ikrafttredelse innen utgangen av oktober er ingen vedtatt dato. Forslaget omfatter også Longyearbyen og Ny-Ålesund.</p>
        <p className="mt-3 text-xs font-semibold text-amber-900">Sist kontrollert: 4. oktober 2026.</p><SourceLine href={sources.proposal} label="Tariffnemnda – pågående sak og forskriftsutkast" />
      </aside>
      <BookbeatAd className="mx-auto mt-8 max-w-[920px]" placement="overview-between-sections" />
      <div className="mx-auto mt-7 max-w-[920px]">
        <p className="mb-4 text-sm leading-6 text-slate-700"><strong>Bilbransjen fikk lovpålagt minstelønn først 15. juni 2026.</strong> Grafen viser historiske tariffsatser i Biloverenskomsten, ikke historisk lovpålagt minstelønn.</p>
        <AutomotiveTariffChart points={biloverenskomstenTariffHistory} />
      </div>
      <nav aria-labelledby="innhold" className="mx-auto mt-7 max-w-[920px] rounded-[11px] border border-slate-200 bg-slate-50 p-5 sm:px-7"><h2 className="text-xl font-bold text-slate-950" id="innhold">Innhold på siden</h2><ol className="mt-3 grid sm:grid-cols-2">{sections.map(([id, label], index) => <li key={id}><a className="grid grid-cols-[2rem_1fr] rounded-[7px] px-2 py-1.5 text-slate-800 hover:bg-white hover:text-[#15533d]" href={"#" + id}><span className="text-xs text-slate-400">{String(index + 1).padStart(2, "0")}</span><span className="font-medium">{label}</span></a></li>)}</ol></nav>
      <div className="mx-auto mt-8 max-w-[920px] min-w-0">
        <Section id="virkeomrade" title="Hvem omfattes av minstelønnen?"><p>Forskriften gjelder ansatte innen bilbransjen, blant annet reparasjon, service, vedlikehold, lakkering, oppretting og lagerarbeid. Arbeidstilsynet bekrefter at også bilpleie, hjulskift og hjullagring omfattes.</p><InfoGrid items={[["Verksted og skadereparasjon", "Bilmekanikere, kjøretøymekanikere, bilskadereparatører, opprettere og billakkerere."], ["Bilpleie og dekk", "Bilpleiere, bilklargjørere, dekkmontører, hjulskiftere og dekkhotellmedarbeidere."], ["Relevant lagerarbeid", "Delelager og lagerarbeid i virksomheter som omfattes av forskriften."]]} /><p>Arbeidet og virksomheten avgjør virkeområdet. En stillingstittel eller SSB-kode er ikke alene nok til å avgjøre om reglene gjelder.</p><SourceLine href={sources.regulation} label="Forskriften § 2" /><div className="rounded-[9px] border border-slate-200 bg-slate-50 p-5 sm:p-6"><h3 className="font-bold text-slate-950">Se lønn for relevante yrker</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{relatedOccupations.map((occupation) => <li className="flex items-start gap-2 text-sm leading-6" key={occupation.href}><span aria-hidden="true" className="mt-2 size-1.5 shrink-0 rounded-full bg-[#15533d]" /><Link className="font-semibold text-[#15533d] hover:underline" href={occupation.href}>{occupation.label}</Link></li>)}</ul><p className="mt-3 text-xs leading-5 text-slate-500">Yrkesgruppene i lønnsstatistikken kan omfatte arbeid utenfor bilbransjen. Arbeidet og virksomheten avgjør om minstelønnsforskriften gjelder.</p></div></Section>
        <Section id="fagarbeider" title="Fagarbeider eller hjelpearbeider?"><p>Nyutlærte fagarbeidere skal minst ha {formatRate(current.newlyQualifiedSkilled)} per time. Etter ett års praksis er satsen {formatRate(current.skilledOneYear)}. Biloverenskomsten bygger fagarbeiderstatus på bestått fagprøve i bilfaget, etter læretid eller praksisløp. Ett års erfaring uten fagbrev gjør deg ikke automatisk til fagarbeider.</p><div className="grid gap-4 sm:grid-cols-2"><InfoCard title="Hjelpearbeider fra fylte 18 år">Minst {formatRate(current.helper18Plus)} per time, og {formatRate(current.helperOneYear)} etter ett års praksis.</InfoCard><InfoCard title="16 eller 17 år?">Forskriften har ingen egen allmenngjort hjelpearbeidersats under 18 år. Lønnen må vurderes etter arbeidsavtalen og eventuell tariffavtale.</InfoCard></div><SourceLine href={sources.regulation} label="Forskriften § 3" /><SourceLine href={sources.agreements} label="Fellesforbundet – Biloverenskomsten" /></Section>
        <Section id="praksis" title="Hva betyr ett års praksis?"><p>Forskriften har to terskler: nyutlært fagarbeider går over til fagarbeidersatsen etter ett års praksis, og hjelpearbeider som har fylt 18 år går over til den høyere hjelpearbeidersatsen etter ett års praksis.</p><p>Den gir ingen detaljert modell for omregning av deltidsarbeid eller avbrutte arbeidsforhold. Ta vare på dokumentasjon og avklar grensetilfeller med arbeidsgiver eller fagforeningen.</p></Section>
        <Section id="bilpleie" title="Minstelønn i bilpleie, bilvask, dekkskift og dekkhotell"><p>Manuell bilpleie og bilvask, hjulskift og hjullagring er omfattet. Manuell bilpleie kan blant annet være innvendig og utvendig håndvask, motor- og understellsvask, felgrens, polering, lakkrens og enkelte småskadereparasjoner.</p><p>Fra 15. juni 2026 må virksomheter i Arbeidstilsynets godkjenningsordning dokumentere at de følger kravene til minstelønn, arbeidstøy og vernefottøy. Dette gjelder også virksomheter som allerede var godkjent.</p><SourceLine href={sources.approval} label="Arbeidstilsynet – godkjenningsordningen" /></Section>
        <Section id="unntak" title="Viktige unntak"><DataTable headers={["Virksomhet eller arbeidsforhold", "Omfattet av forskriften?"]} rows={[["Bilverksted, billakkering og biloppretting", "Ja"], ["Bilpleie, manuell bilvask, dekkskift og dekkhotell", "Ja"], ["Delelager i relevant bilvirksomhet", "Ja"], ["Virksomhet som hovedsakelig kjøper og selger kjøretøy", "Nei"], ["Virksomhet som hovedsakelig driver ruteskift/bilglassreparasjon", "Nei"], ["Virksomhet som hovedsakelig driver bensinstasjon", "Nei"], ["Lærlinger og personer på arbeidsmarkedstiltak", "Nei"], ["Bedrift med tariffavtale inngått med fagforening med innstillingsrett", "Nei – følger tariffavtalen"]]} /><p>En bensinstasjon kan ha en juridisk adskilt virksomhet som utfører reparasjon, service eller vedlikehold og dermed omfattes. Biloverenskomstens tariffregler for bensinekspeditører betyr ikke at bensinstasjoner generelt omfattes av allmenngjøringen.</p><p>Forskriften gjelder heller ikke dersom arbeidstakeren samlet sett har gunstigere lønns- og arbeidsvilkår etter avtale eller den retten som ellers gjelder for arbeidsforholdet.</p><SourceLine href={sources.regulation} label="Forskriften §§ 2 og 5" /></Section>
        <BookbeatAd className="my-8 sm:my-10" placement="minimum-wage-mid-content" />
        <Section id="arbeidstoy" title="Arbeidsgiver betaler nødvendig arbeidstøy og vernesko"><p>Arbeidsgiver skal uten kostnad for deg sørge for nødvendig arbeidstøy og vernefottøy, tilpasset arbeidsplassen og arbeidet og i tråd med HMS-kravene. Dette er et allmenngjort arbeidsvilkår.</p><p>Arbeidstilsynets veiledning sier også at utstyret må holde kvalitet for normal bruk, og at virksomheten må ha ordninger for vask eller rens av arbeidstøyet.</p><SourceLine href={sources.regulation} label="Forskriften § 4" /></Section>
        <Section id="overtid" title="Overtid og arbeidstid"><p>Bilforskriften fastsetter ingen egen overtidsprosent eller kortere arbeidsuke. Arbeidsmiljølovens regler gjelder, og arbeidsavtale eller tariffavtale kan gi bedre rettigheter. Ved faktisk overtidsarbeid er lovens minimum 40 prosent tillegg til den avtalte ordinære timelønnen.</p><DataTable headers={["Avtalt ordinær timelønn i eksemplet", "Med minst 40 % overtidstillegg"]} rows={[[formatRate(current.newlyQualifiedSkilled), formatRate(current.newlyQualifiedSkilled * 1.4)], [formatRate(current.skilledOneYear), formatRate(current.skilledOneYear * 1.4)]]} /><p>Eksemplene forutsetter at avtalt timelønn er lik minstesatsen. Tjener du mer, skal tillegget beregnes av den høyere lønnen. Merarbeid for deltidsansatte er ikke automatisk overtid bare fordi arbeidet overstiger avtalt stillingsprosent. Tariffavtale kan gi bedre rettigheter.</p><SourceLine href={sources.overtime} label="Arbeidstilsynet – overtid og merarbeid" /></Section>
        <Section id="tariff" title="Hvorfor er lovsatsen 223,50 når tariffen er 249 kroner?"><p>Den første forskriften bygger på Biloverenskomsten 2024–2026 og satsene etter mellomoppgjøret i 2025. Den nye Biloverenskomsten 2026–2028 har høyere minstesatser. Tariffoppgjøret endrer ikke automatisk forskriften.</p><DataTable headers={["Arbeidstaker", "Lovpålagt per time", "Biloverenskomsten 2026–2028"]} rows={automotiveCategories.map((item) => [item.label, formatRate(current[item.key]), formatRate(tariff[item.key])])} /><div className="grid gap-4 sm:grid-cols-2"><InfoCard title="Allmenngjort minstelønn">Gjelder arbeidstakere innen forskriftens virkeområde, med de uttrykkelige unntakene.</InfoCard><InfoCard title="Tariffbundne arbeidsforhold">Ansatte i bedrifter med tariffavtale inngått med fagforening med innstillingsrett er unntatt fra forskriften. De følger tariffavtalen.</InfoCard></div><SourceLine href={sources.tariff} label="Fellesforbundet – Biloverenskomsten 2026" /></Section>
        <Section id="tillegg" title="Kveld, natt, helg, skift og smusstillegg"><p>Forskriften gir ingen generelle lovpålagte satser for kveld, natt, helg, skift, smuss eller arbeid på større kjøretøy. Rettigheter til slike tillegg kan følge av tariffavtale eller arbeidsavtale.</p><InfoCard title="Tariff – ikke allmenngjort minstelønn">2026-oppgjøret setter smusstillegget til minst 9,50 kr per mønstret time og minst 36,10 kr per jobb. Tillegget for arbeid med større enheter/diesel er 11,00 kr. Vilkårene i tariffavtalen avgjør når tilleggene gjelder.</InfoCard><SourceLine href={sources.tariff} label="Fellesforbundet – tariffbestemmelser om tillegg" /></Section>
        <Section id="historikk" title="Lovhistorikk fra 2026 – tariffhistorikk fra 2016"><p><strong>Bilbransjen fikk lovpålagt minstelønn først 15. juni 2026.</strong> Biloverenskomsten hadde ikke vært allmenngjort tidligere. Grafen før innholdsfortegnelsen og tariffhistorikken nedenfor viser Biloverenskomstens tariffsatser, ikke historisk lovpålagt minstelønn.</p><DataTable headers={["Periode", "Lovpålagt minstelønn etter Biloverenskomsten"]} rows={[["2016–14.06.2026", "Ingen allmenngjort minstelønn"], ["Fra 15.06.2026", automotiveCategories.map((item) => formatRate(current[item.key])).join(" / ")]]} /><DataTable minWidth="760px" headers={["Fra / avtale", "Nyutlært fagarbeider", "Fagarbeider ≥1 år", "Hjelpearbeider 18+", "Hjelpearbeider ≥1 år"]} rows={biloverenskomstenTariffHistory.map((point) => [point.period, ...automotiveCategories.map((item) => formatRate(point[item.key]))])} /><p>Nyutlærtsatsen økte fra 162,00 til 249,00 kroner mellom 2016 og 2026: 87 kroner per time, eller omtrent 53,7 prosent nominelt. Dette er ikke justert for prisvekst. Tabellen viser oppgitte avtaleendringer, ikke en ny sats for hvert kalenderår.</p><SourceLine href={sources.agreements} label="Fellesforbundet – Biloverenskomsten og tariffavtaler" /></Section>
        <Section id="faktisk-lonn" title="Minstelønn er ikke det samme som vanlig lønn"><p>Minstelønnen er et gulv. SSB-statistikken viser hva bilmekanikere faktisk tjener. For yrkesgruppe 7231 i {salaryData.period}, begge kjønn, alle sektorer og heltid og deltid samlet, er månedslønnen:</p><div className="grid gap-4 sm:grid-cols-2"><Comparison label="Gjennomsnittlig månedslønn" rate={salary.average} /><Comparison label="Median månedslønn" rate={salary.value} /></div><p>SSBs månedslønn er omregnet til heltidsekvivalenter og er et annet mål enn lovpålagt timelønn. Se flere tall og forklaringer på <Link className="font-semibold text-[#15533d] hover:underline" href={salary.href}>yrkessiden for bilmekanikere</Link> og i <Link className="font-semibold text-[#15533d] hover:underline" href="/blogg/lonn-alder-og-kjonnsforskjeller-blant-bilmekanikere">artikkelen om lønn, alder og kjønnsforskjeller</Link>.</p><SourceLine href={sources.ssb} label="SSB tabell 11418 – månedslønn 2025" /></Section>
        <BookbeatAd className="my-8 sm:my-10" placement="minimum-wage-before-faq" />
        <Section id="faq" title="Ofte stilte spørsmål"><div className="divide-y divide-slate-200 overflow-hidden rounded-[5px] border border-black/10 bg-white">{faq.map((item) => <details className="group px-5 py-4 open:bg-[#fbfbf8]" key={item.question}><summary className="cursor-pointer list-none pr-8 font-semibold text-slate-950 marker:hidden">{item.question}<span aria-hidden="true" className="float-right text-[#15533d] group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{item.answer}</p></details>)}</div></Section>
        <Section id="kilder" title="Kilder og metode"><p>Gjeldende satser er kontrollert 4. oktober 2026 mot Arbeidstilsynet og forskrift FOR-2026-04-13-592. Ikrafttredelsen ble korrigert til 15. juni 2026. Forslaget til nye satser har ingen vedtatt ikrafttredelsesdato.</p><p>Lovsatsene, forslaget og tariffhistorikken er separate datasett. SSB-tallene hentes fra prosjektets eksisterende lønnsdatasett for 2025. Tariffhistorikken viser de oppgitte satsendringene i Biloverenskomsten; den brukes ikke som lovhistorikk.</p><ul className="space-y-2 text-sm font-semibold text-[#15533d]">{[[sources.rates, "Arbeidstilsynet – gjeldende minstelønn"], [sources.regulation, "Lovdata – bilforskriften"], [sources.proposal, "Tariffnemnda – fortsatt allmenngjøring"], [sources.tariff, "Fellesforbundet – tariffoppgjøret 2026"], [sources.agreements, "Fellesforbundet – tariffavtaler"], [sources.tariff2016, "LO – historiske minstesatser 2016"], [sources.tariff2018, "Biloverenskomsten 2018–2020"], [sources.tariff2023, "Mellomoppgjøret 2023"], [sources.tariff2024, "Biloverenskomsten 2024–2026"], [sources.tariff2025, "Mellomoppgjøret 2025"], [sources.approval, "Arbeidstilsynet – bilpleie, hjulskift og hjullagring"], [sources.overtime, "Arbeidstilsynet – overtid"], [sources.ssb, "SSB – tabell 11418"]].map(([href, label]) => <li key={href}><a className="hover:underline" href={href}>{label} ↗</a></li>)}</ul></Section>
          <section aria-labelledby="videre-title" className="mt-14 overflow-hidden rounded-[18px] border border-[#cfded6] bg-[#f7faf8] shadow-[0_18px_50px_rgba(15,23,42,0.06)]">
            <div className="border-b border-[#dce7e1] bg-white px-5 py-6 sm:px-8 sm:py-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--primary)]">Utforsk videre</p><h2 className="mt-2 text-[1.75rem] font-bold leading-[1.15] tracking-[-0.03em] text-slate-950 sm:text-[2.1rem]" id="videre-title">Fra minstelønn til faktisk lønn i bilbransjen</h2><p className="mt-3 max-w-3xl text-base leading-7 text-slate-700">Minstelønn er et lovpålagt gulv, ikke det samme som vanlig lønn i yrket. Bruk lønnsverktøyene eller les mer om lønn i bilbransjen og lønnsforhandling.</p><Link className="mt-5 inline-flex items-center gap-2 rounded-[8px] bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[var(--primary-strong)]" href="/yrke/bilmekanikere-lonn">Se hva bilmekanikere faktisk tjener <span aria-hidden="true">→</span></Link></div>
            <div className="grid gap-8 px-5 py-6 sm:px-8 sm:py-8 lg:grid-cols-2"><div><h3 className="text-lg font-bold text-slate-950">Nyttige lønnsverktøy</h3><div className="mt-4 grid gap-2">{salaryTools.map((item) => <Link className="group flex items-center justify-between gap-4 rounded-[10px] border border-slate-200 bg-white px-4 py-3 transition hover:border-[#9fc5b5] hover:shadow-sm" href={item.href} key={item.href}><span><strong className="block text-sm text-slate-950 group-hover:text-[var(--primary)]">{item.label}</strong><span className="mt-0.5 block text-xs leading-5 text-slate-500">{item.description}</span></span><span aria-hidden="true" className="shrink-0 text-lg text-[var(--primary)]">→</span></Link>)}</div></div><div><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-lg font-bold text-slate-950">Anbefalte artikler</h3><Link className="text-xs font-semibold text-[var(--primary)] hover:underline" href="/blogg/kategori/lonnsforhandling">Alle om lønnsforhandling →</Link></div><div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{recommendedArticles.map((article) => <Link className="group flex items-start justify-between gap-4 py-3.5" href={article.href} key={article.href}><span><span className="block text-[11px] font-bold uppercase tracking-[0.1em] text-slate-500">{article.category}</span><strong className="mt-1 block text-sm leading-5 text-slate-950 group-hover:text-[var(--primary)] group-hover:underline">{article.label}</strong></span><span aria-hidden="true" className="mt-3 shrink-0 text-lg text-[var(--primary)]">→</span></Link>)}</div></div></div>
          </section>
      </div>
    </div>
  </main>;
}
function Section({ children, id, title }: { children: ReactNode; id: string; title: string }) { return <section className="scroll-mt-6 space-y-6 py-10 first:pt-0 [&>p]:max-w-3xl [&>p]:text-[1.03rem] [&>p]:leading-[1.8] [&>p]:text-slate-950 sm:[&>p]:text-lg" id={id}><h2 className="text-balance text-[1.75rem] font-bold leading-[1.15] tracking-[-0.03em] text-slate-950 sm:text-[2.1rem]">{title}</h2>{children}</section>; }
function InfoCard({ children, title }: { children: ReactNode; title: string }) { return <article className="rounded-[8px] border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{children}</p></article>; }
function InfoGrid({ items }: { items: readonly (readonly [string, string])[] }) { return <div className="grid gap-4 md:grid-cols-3">{items.map(([heading, text]) => <InfoCard key={heading} title={heading}>{text}</InfoCard>)}</div>; }
function Comparison({ label, rate }: { label: string; rate: number }) { return <article className="rounded-[9px] border border-[#d8eadf] bg-[#f3faf5] p-5"><p className="font-semibold text-slate-950">{label}</p><p className="mt-3 text-3xl font-bold tabular-nums text-[#15533d]">{formatRate(rate)}<span className="ml-2 text-sm font-medium text-slate-500">/måned</span></p></article>; }
function SourceLine({ href, label }: { href: string; label: string }) { return <p className="text-xs leading-5 text-slate-500">Kilde: <a className="font-semibold text-[#15533d] hover:underline" href={href}>{label} ↗</a></p>; }
function DataTable({ headers, minWidth = "620px", rows }: { headers: string[]; minWidth?: string; rows: ReactNode[][] }) { return <div className="overflow-x-auto rounded-[5px] border border-black/10 bg-white"><table className="w-full border-collapse text-left" style={{ minWidth }}><thead className="bg-[#f1f7f2] text-sm text-slate-700"><tr>{headers.map((header) => <th className="px-4 py-3 font-semibold" key={header}>{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-200 text-sm text-slate-800">{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td className="px-4 py-3.5" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }

function formatDate(value: string) { return new Intl.DateTimeFormat("nb-NO", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
