import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { ArticleBreadcrumbs } from "@/components/article-breadcrumbs";
import { BookbeatAd } from "@/components/bookbeat-ad";
import { StickyLeftAdRail } from "@/components/sticky-left-ad-rail";
import { CoachMinimumWageChart } from "@/components/coach-minimum-wage-chart";
import { coachMinimumWage as current, coachMinimumWageProposal as proposal, coachTariff2026 as tariff, coachSources as sources, coachMinimumWageHistory, coachFaq as faq, formatCoachRate as formatRate } from "@/lib/coach-minimum-wage";
import { getOccupationDetailViewModelBySlug } from "@/lib/occupation-detail-view-models";
import { getAbsoluteUrl, siteConfig } from "@/lib/site-config";

const pagePath = "/minstelonn/minstelonn-turbil";
const title = "Minstelønn turbil 2026 – turbuss og bussjåfør";
const description = "Se minstelønn for persontransport med turbil i 2026. Finn gjeldende sats for turbussjåfører, regler om overtid, kost og losji, tariff og historikk.";
const image = "/images/minimum-wage/turbil-hero.png";
export const metadata: Metadata = {
  title, description, alternates: { canonical: pagePath },
  openGraph: { type: "website", locale: "nb_NO", url: pagePath, siteName: siteConfig.name, title, description, images: [{ url: image, alt: "Turbuss ved en norsk fjord" }] },
  twitter: { card: "summary_large_image", title, description, images: [image] },
};
const sections = [["virkeomrade", "Hvem gjelder minstelønnen for?"], ["rutebuss", "Turbuss eller konkurranseutsatt rutebuss?"], ["tariff", "Lovpålagt minstelønn og fagbrev"], ["overtid", "Overtidsbetaling"], ["historikk", "Historiske satser"], ["faktisk-lonn", "Hva tjener bussjåfører?"], ["faq", "Ofte stilte spørsmål"]] as const;
const relatedOccupations = [{ label: "Bussjåfører og trikkeførere", href: "/yrke/bussjaforer-og-trikkeforere-lonn" }] as const;
const salaryTools = [
  { href: "/yrker", label: "Alle yrker", description: "Utforsk lønnstall for hundrevis av yrker" },
  { href: "/lonnsjekk", label: "Lønnsjekk", description: "Sammenlign lønnen din med relevant statistikk" },
  { href: "/jobbtilbud", label: "Lønnstilbud", description: "Vurder lønnen i et nytt jobbtilbud" },
  { href: "/lonnskalkulator", label: "Lønnskalkulator", description: "Regn om mellom års-, måneds- og timelønn" },
] as const;


const recommendedArticles = [
  { href: "/blogg/5-ting-du-bor-ha-klart-for-lonnssamtalen", label: "5 ting du bør ha klart før lønnssamtalen", category: "Lønnsforhandling" },
  { href: "/blogg/7-gode-argumenter-for-a-be-om-hoyere-lonn", label: "7 gode argumenter for å be om høyere lønn", category: "Lønnsforhandling" },
] as const;

export default async function CoachMinimumWagePage() {
  const busModel = await getOccupationDetailViewModelBySlug("bussjaforer-og-trikkeforere-lonn");
  const busSalary = busModel?.data.distribution;
  const structuredData = [
    { "@context": "https://schema.org", "@type": "WebPage", name: title, description, url: getAbsoluteUrl(pagePath), inLanguage: "nb-NO", dateModified: current.verifiedAt },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Hjem", item: getAbsoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "Minstelønn", item: getAbsoluteUrl("/minstelonn") }, { "@type": "ListItem", position: 3, name: "Turbil", item: getAbsoluteUrl(pagePath) }] },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
  ];
  return <main className="min-h-screen bg-white px-4 pb-16 pt-5 sm:px-6 lg:px-8">
    {structuredData.map((data, index) => <script dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} key={index} type="application/ld+json" />)}
    <div className="relative mx-auto max-w-7xl">
      <StickyLeftAdRail />
      <ArticleBreadcrumbs href="/minstelonn" section="Minstelønn" title="Turbil" />
      <div className="relative mx-auto mt-7 max-w-[1080px] overflow-hidden rounded-[28px] bg-[radial-gradient(circle_at_70%_25%,#f3ead4_0%,#fbfdf9_38%,#e8f3e9_100%)] px-5 pb-8 pt-8 sm:px-10 lg:min-h-[410px] lg:px-[250px] lg:pb-10 lg:pt-10">
        <div aria-hidden="true" className="absolute -left-20 bottom-[-95px] size-72 rounded-full bg-[#b9d6ae]/50" /><div aria-hidden="true" className="absolute -right-12 top-4 size-56 rounded-[45%] bg-[#e4cf91]/35" />
        <div className="absolute right-8 top-8 hidden h-[330px] w-[220px] overflow-hidden rounded-[46%_46%_18%_46%] lg:block"><Image alt="Mørkegrønn turbuss ved en norsk fjord med fjell i bakgrunnen" className="h-full w-full object-cover object-[60%_70%]" fill priority sizes="220px" src="/images/minimum-wage/turbil-hero.png" /></div>
        <header className="relative z-10 mx-auto max-w-3xl text-center">
          <p className="inline-flex rounded-full bg-[#e4f2e7] px-5 py-2 text-xs font-bold uppercase tracking-[0.17em] text-[#15533d]">Persontransport med turbil</p>
          <h1 className="mx-auto mt-6 text-[clamp(2.45rem,5vw,4.8rem)] font-[760] leading-[1.03] tracking-[-0.035em] text-[#101820]">Minstelønn for persontransport med turbil</h1>
          <p className="mx-auto mt-5 max-w-[690px] text-base leading-[1.65] text-[#3f4a45] sm:text-[1.12rem]">Sjåfører som utfører persontransport med turvogn eller buss og omfattes av allmenngjøringsforskriften, skal minst ha <strong>{formatRate(current.hourlyRate)} per time</strong>. Her finner du gjeldende sats, hvem den gjelder for, historisk utvikling og forskjellen mellom lovpålagt minstelønn og Bussbransjeavtalen.</p>
          <div className="mx-auto mt-7 grid max-w-[650px] gap-3 text-sm text-[#52627d] sm:grid-cols-3"><p><strong className="block text-[#15533d]">Gjeldende fra</strong>{formatDate(current.effectiveFrom)}</p><p><strong className="block text-[#15533d]">Lovpålagt timelønn</strong>{formatRate(current.hourlyRate)}/time</p><p><strong className="block text-[#15533d]">Sist kontrollert</strong>{formatDate(current.verifiedAt)}</p></div>
        </header>
        <div className="relative z-10 mx-auto mt-6 h-44 w-full max-w-sm overflow-hidden rounded-[28px] sm:h-52 lg:hidden"><Image alt="Mørkegrønn turbuss ved en norsk fjord med fjell i bakgrunnen" className="h-full w-full object-cover object-[50%_72%]" fill priority sizes="(max-width: 1024px) 384px, 0px" src="/images/minimum-wage/turbil-hero.png" /></div>
      </div>



      <div className="mx-auto mt-9 grid max-w-[1000px] gap-4 sm:grid-cols-3">
        <article className="rounded-[11px] border border-[#15533d] bg-[linear-gradient(135deg,#1d634c,#104733)] px-5 py-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.12em]">Lovpålagt · fra 15. juni 2025</p><p className="mt-3 text-4xl font-bold tabular-nums tracking-[-0.05em]">{formatRate(current.hourlyRate)}</p><p className="mt-3 text-xs leading-5 text-white/80">Per time for arbeidstakere som omfattes. Én sats uten egne trinn for fagbrev, alder eller ansiennitet.</p><a className="mt-3 inline-block text-xs font-semibold underline" href={sources.regulation}>Se gjeldende forskrift ↗</a></article>
        <article className="rounded-[11px] border border-[#d8eadf] bg-[#f3faf5] px-5 py-6 text-[#19243b]"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#15533d]">Virkeområde</p><p className="mt-3 text-2xl font-bold">Turbil og turbuss</p><p className="mt-3 text-xs leading-5 text-[#52627d]">Transporten må være utenfor konkurransetildeling av løyve etter yrkestransportlova § 8. Ikke alle bussjåfører omfattes.</p></article>
        <article className="rounded-[11px] border border-[#d8eadf] bg-[#f3faf5] px-5 py-6 text-[#19243b]"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#15533d]">Allmenngjort vilkår</p><p className="mt-3 text-2xl font-bold">Kost og losji</p><p className="mt-3 text-xs leading-5 text-[#52627d]">Arbeidsgiver skal dekke mat og overnatting når bestemmelsen kommer til anvendelse.</p></article>
      </div>
      <aside className="mx-auto mt-7 max-w-[920px] rounded-[11px] border border-amber-700/25 bg-amber-50 p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.14em] text-amber-800">Under behandling · 2026</p><h2 className="mt-2 text-xl font-semibold text-slate-950">{formatRate(proposal.hourlyRate)} foreslått som ny minstelønn</h2><p className="mt-2 text-sm leading-6 text-slate-700">Forslaget er ikke vedtatt og har ingen fastsatt ikrafttredelsesdato. Dagens lovpålagte sats er fortsatt <strong>{formatRate(current.hourlyRate)} per time</strong>. Bussbransjeavtalens turbilkapittel har allerede en tariffsats på {formatRate(tariff.withoutCertificate)} uten fagbrev.</p><p className="mt-3 text-xs font-semibold text-amber-900">Sist kontrollert: {formatDate(current.verifiedAt)}.</p><SourceLine href={sources.proposal} label="Tariffnemnda – turbil 2026" /></aside>
      <BookbeatAd className="mx-auto mt-8 max-w-[920px]" placement="overview-between-sections" />
      <div className="mx-auto mt-7 max-w-[920px]"><CoachMinimumWageChart endDate={current.verifiedAt} points={coachMinimumWageHistory} /></div>
      <nav aria-labelledby="innhold" className="mx-auto mt-7 max-w-[920px] rounded-[11px] border border-slate-200 bg-slate-50 p-5 sm:px-7"><h2 className="text-xl font-bold text-slate-950" id="innhold">Innhold på siden</h2><ol className="mt-3 grid sm:grid-cols-2">{sections.map(([id, label], index) => <li key={id}><a className="grid grid-cols-[2rem_1fr] rounded-[7px] px-2 py-1.5 text-slate-800 hover:bg-white hover:text-[#15533d]" href={"#" + id}><span className="text-xs text-slate-400">{String(index + 1).padStart(2, "0")}</span><span className="font-medium">{label}</span></a></li>)}</ol></nav>
      <div className="mx-auto mt-8 max-w-[920px] min-w-0">
        <Section id="virkeomrade" title="Hvem gjelder minstelønnen for?"><p>Forskriften omfatter ansatte i bedrifter som utfører persontransport med turvogn eller buss, når transporten ikke krever tildeling av løyve ved konkurranse etter yrkestransportlova § 8. Navnet «bussjåfør» avgjør ikke alene om du omfattes.</p><InfoCard title="Gjelder 218,62 kroner for deg?"><span className="block">1. Kjører du persontransport med turvogn eller buss?</span><span className="mt-2 block">2. Er transporten utenfor ordningen med konkurransetildelt løyve etter § 8?</span><span className="mt-3 block">To ja-svar peker mot at transporten kan omfattes. Lærlinger og personer på arbeidsmarkedstiltak er unntatt. Ved tvil må virksomheten og det konkrete transportoppdraget avklares.</span></InfoCard><div className="rounded-[9px] border border-slate-200 bg-slate-50 p-5 sm:p-6"><h3 className="font-bold text-slate-950">Se lønn for relevante yrker</h3><ul className="mt-3 space-y-2">{relatedOccupations.map((occupation) => <li key={occupation.href}><Link className="font-semibold text-[#15533d] hover:underline" href={occupation.href}>{occupation.label} →</Link></li>)}</ul><p className="mt-3 text-xs leading-5 text-slate-500">SSB-kode 8331 inkluderer også trikkeførere og bussjåfører utenfor forskriftens virkeområde.</p></div><SourceLine href={sources.regulationText} label="Arbeidstilsynet – forskriften § 2" /></Section>
        <Section id="rutebuss" title="Turbuss eller konkurranseutsatt rutebuss?"><p>Den sentrale grensen er om transporten krever konkurransetildeling av løyve etter yrkestransportlova § 8. Vanlig rutebuss og turkjøring kan følge forskjellige lønnsregler.</p><DataTable headers={["Transport eller arbeidstaker", "Denne forskriften"]} rows={[["Turbuss innenfor virkeområdet", "Ja"], ["Buss uten konkurransetildelt løyve etter § 8", "Ja, når øvrige vilkår er oppfylt"], ["Transport som krever konkurransetildelt løyve etter § 8", "Nei"], ["Lærlinger og personer på arbeidsmarkedstiltak", "Nei"]]} /><InfoCard title="Konkurranseutsatt kjøring har andre lønnskrav">Etter yrkestransportlova § 8 femte ledd må den som får løyve gjennom konkurranse sikre ansatte som arbeider direkte på kontrakten, lønns- og arbeidsvilkår minst på nivå med gjeldende landsomfattende tariffavtale eller det som ellers er normalt for stedet og yrket. Plikten gjelder også underleverandører.</InfoCard><h3 className="text-xl font-bold text-slate-950">Hva menes med turbil?</h3><p>Bussbransjeavtalens turbilkapittel omfatter busskjøring utenfor ordinær rutekjøring og kontraktkjøring. Tariffens inndeling er likevel ikke en fullstendig fasit for allmenngjøringen: Her er forskriftens juridiske virkeområde styrende.</p><p>Drosje og persontransport med kjøretøy registrert for inntil ni personer har et eget løyveregelverk. Drosjesjåfører og Uber-/Bolt-lignende tjenester omfattes ikke automatisk av turbilforskriften.</p><SourceLine href={sources.transportLaw} label="Yrkestransportlova §§ 8 og 9" /><SourceLine href={sources.tariffAgreement} label="Bussbransjeavtalen – turbilkapittelet" /></Section>
        <Section id="tariff" title="218,62 eller 229,62 kroner: lovpålagt minstelønn og fagbrev"><p>Allmenngjøringen har ett lovpålagt lønnsgulv på {formatRate(current.hourlyRate)} per time. Fagbrev gir ingen egen høyere sats i forskriften. Når Bussbransjeavtalen gjelder, har turbilkapittelet derimot ulike satser med og uten fagbrev.</p><DataTable headers={["Kategori", "Lovpålagt per time", "Tariff 2026 per time"]} rows={[["Uten fagbrev", formatRate(current.hourlyRate), formatRate(tariff.withoutCertificate)], ["Med fagbrev", formatRate(current.hourlyRate), formatRate(tariff.withCertificate)], ["Gjelder fra", formatDate(current.effectiveFrom), formatDate(tariff.effectiveFrom)], ["Status", "Gjeldende allmenngjort gulv", "Bussbransjeavtalen – tariff"]]} /><p>Fellesforbundets tabell for 1. april 2025 viste 218,62 kroner uten fagbrev og 232,62 kroner med fagbrev. Oppgjøret i 2026 løftet alle tariffens minstelønnssatser med 11 kroner fra 1. april, til henholdsvis 229,62 og 243,62 kroner. Resultatet ble godkjent i uravstemningen.</p><InfoCard title="Tariffendringen endrer ikke lovsatsen automatisk">Forslaget til ny allmenngjøring bruker {formatRate(proposal.hourlyRate)} som ett nytt lovgulv. Det innebærer ikke at tariffens fagbrevsats på {formatRate(tariff.withCertificate)} er foreslått som en egen allmenngjort sats.</InfoCard><SourceLine href={sources.tariff2025} label="Fellesforbundet – lønnstabell 2025, turbil kapittel 10" /><SourceLine href={sources.tariff} label="Fellesforbundet – oppgjøret 2026" /><SourceLine href={sources.tariffApproved} label="Fellesforbundet – godkjent uravstemning" /></Section>
        <BookbeatAd className="my-8 sm:my-10" placement="minimum-wage-mid-content" />
        <Section id="overtid" title="Overtidsbetaling for turbilsjåfører"><p>Ved faktisk overtidsarbeid er lovens minimum 40 prosent tillegg til <strong>avtalt ordinær timelønn</strong>, med mindre en bedre ordning gjelder. Turbilforskriften har ingen egen høyere overtidsprosent.</p><InfoCard title="Eksempel når avtalt timelønn er 218,62 kroner">{formatRate(current.hourlyRate)} × 1,40 = {formatRate(current.hourlyRate * 1.4)} per time. Eksemplet gjelder bare når minstesatsen også er din avtalte ordinære timelønn.</InfoCard><p>Har du høyere avtalt lønn, beregnes tillegget av den høyere satsen. Ekstra arbeidstid er ikke automatisk overtid etter loven. Arbeidstidsordningen og eventuell tariffavtale må vurderes.</p><SourceLine href={sources.overtime} label="Arbeidstilsynet – overtid" /></Section>
        <Section id="historikk" title="Historiske lovpålagte minstelønnssatser"><p>Turbilområdet har en sammenhengende allmenngjort sats gjennom hele perioden 2016–2026. Tabellen og grafen viser lovpålagte satser, uten den foreslåtte økningen i 2026.</p><DataTable headers={["Gyldig periode", "Lovpålagt minstelønn per time"]} rows={coachMinimumWageHistory.map((point, index) => [(index === 0 ? "01.01.2016" : formatShortDate(point.effectiveFrom)) + (point.effectiveTo ? "–" + formatShortDate(point.effectiveTo) : "–nå"), formatRate(point.hourlyRate)])} /><InfoCard title="Første ikrafttredelse var 1. oktober 2015">Den opprinnelige datoen 1. august 2015 ble utsatt før forskriften trådte i kraft. Endringsforskriften av 23. juli 2015 fastsatte 1. oktober. Datagrunnlaget begynner derfor 1. oktober 2015, mens grafen viser perioden fra 2016.</InfoCard><p>Fra 150,00 kroner i 2016 til 218,62 kroner har lovgulvet økt med 68,62 kroner per time, omtrent 45,7 prosent nominelt. Økningen er ikke justert for prisvekst.</p><p>For 2018 brukes den opprinnelige satsen 155,87 kroner, som også er gjengitt i Tariffnemndas 2019-protokoll. Senere konsoliderte forskrifter kan vise satsen 158,37 kroner fra 2019. Historiske lønnssatser betyr ikke at alle dagens øvrige vilkår gjaldt i hele perioden.</p><SourceLine href={sources.postponed2015} label="Lovdata – utsatt ikrafttredelse i 2015" /><SourceLine href={sources.original2019} label="Tariffnemnda – opprinnelig 2018-sats og endring fra juli 2019" /></Section>
        <Section id="faktisk-lonn" title="Hva tjener bussjåfører faktisk?"><p>Minstelønn er et gulv. SSB-statistikken viser faktisk månedslønn for den bredere yrkesgruppen <strong>bussjåfører og trikkeførere (8331)</strong>, ikke bare turbilsjåfører.</p>{busSalary && <><h3 className="text-xl font-bold text-slate-950">Bussjåfører og trikkeførere · {busSalary.periodLabel}</h3><div className="grid gap-4 sm:grid-cols-2">{busSalary.total?.average != null && <Comparison label="Gjennomsnittlig månedslønn" rate={busSalary.total.average} />}{busSalary.total?.median != null && <Comparison label="Median månedslønn" rate={busSalary.total.median} />}</div></>}<p>Tallene fra tabell 11418 gjelder begge kjønn, alle sektorer og heltid og deltid samlet, omregnet til heltidsekvivalenter. Gruppen inkluderer også rutebussjåfører utenfor turbilforskriften og trikkeførere. Månedslønn kan ikke leses som en lovpålagt timesats.</p><p>Se mer på <Link className="font-semibold text-[#15533d] hover:underline" href="/yrke/bussjaforer-og-trikkeforere-lonn">yrkessiden for bussjåfører og trikkeførere</Link>.</p><SourceLine href={sources.ssb} label="SSB – tabell 11418" /></Section>
        <BookbeatAd className="my-8 sm:my-10" placement="minimum-wage-before-faq" />
        <Section id="faq" title="Ofte stilte spørsmål"><div className="divide-y divide-slate-200 overflow-hidden rounded-[5px] border border-black/10 bg-white">{faq.map((item) => <details className="group px-5 py-4 open:bg-[#fbfbf8]" key={item.question}><summary className="cursor-pointer list-none pr-8 font-semibold text-slate-950 marker:hidden">{item.question}<span aria-hidden="true" className="float-right text-[#15533d] group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{item.answer}</p></details>)}</div></Section>
<section aria-labelledby="videre-title" className="mt-14 overflow-hidden rounded-[18px] border border-[#cfded6] bg-[#f7faf8] shadow-[0_18px_50px_rgba(15,23,42,0.06)]">
            <div className="border-b border-[#dce7e1] bg-white px-5 py-6 sm:px-8 sm:py-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--primary)]">Utforsk videre</p><h2 className="mt-2 text-[1.75rem] font-bold leading-[1.15] tracking-[-0.03em] text-slate-950 sm:text-[2.1rem]" id="videre-title">Fra minstelønn til faktisk bussjåførlønn</h2><p className="mt-3 max-w-3xl text-base leading-7 text-slate-700">Minstelønn er et lovpålagt gulv, ikke det samme som vanlig lønn i yrket. Bruk lønnsverktøyene eller les mer om bussjåførlønn og lønnsforhandling.</p><Link className="mt-5 inline-flex items-center gap-2 rounded-[8px] bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[var(--primary-strong)]" href="/yrke/bussjaforer-og-trikkeforere-lonn">Se hva bussjåfører og trikkeførere faktisk tjener <span aria-hidden="true">→</span></Link></div>
            <div className="grid gap-8 px-5 py-6 sm:px-8 sm:py-8 lg:grid-cols-2"><div><h3 className="text-lg font-bold text-slate-950">Nyttige lønnsverktøy</h3><div className="mt-4 grid gap-2">{salaryTools.map((item) => <Link className="group flex items-center justify-between gap-4 rounded-[10px] border border-slate-200 bg-white px-4 py-3 transition hover:border-[#9fc5b5] hover:shadow-sm" href={item.href} key={item.href}><span><strong className="block text-sm text-slate-950 group-hover:text-[var(--primary)]">{item.label}</strong><span className="mt-0.5 block text-xs leading-5 text-slate-500">{item.description}</span></span><span aria-hidden="true" className="shrink-0 text-lg text-[var(--primary)]">→</span></Link>)}</div></div><div><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-lg font-bold text-slate-950">Anbefalte artikler</h3><Link className="text-xs font-semibold text-[var(--primary)] hover:underline" href="/blogg/kategori/lonnsforhandling">Alle om lønnsforhandling →</Link></div><div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{recommendedArticles.map((article) => <Link className="group flex items-start justify-between gap-4 py-3.5" href={article.href} key={article.href}><span><span className="block text-[11px] font-bold uppercase tracking-[0.1em] text-slate-500">{article.category}</span><strong className="mt-1 block text-sm leading-5 text-slate-950 group-hover:text-[var(--primary)] group-hover:underline">{article.label}</strong></span><span aria-hidden="true" className="mt-3 shrink-0 text-lg text-[var(--primary)]">→</span></Link>)}</div></div></div>
          </section>
      </div>
    </div>
  </main>;
}
function Section({ children, id, title }: { children: ReactNode; id: string; title: string }) { return <section className="scroll-mt-6 space-y-6 py-10 first:pt-0 [&>p]:max-w-3xl [&>p]:text-[1.03rem] [&>p]:leading-[1.8] [&>p]:text-slate-950 sm:[&>p]:text-lg" id={id}><h2 className="text-balance text-[1.75rem] font-bold leading-[1.15] tracking-[-0.03em] text-slate-950 sm:text-[2.1rem]">{title}</h2>{children}</section>; }
function InfoCard({ children, title }: { children: ReactNode; title: string }) { return <article className="rounded-[8px] border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{children}</p></article>; }
function Comparison({ label, rate }: { label: string; rate: number }) { return <article className="rounded-[9px] border border-[#d8eadf] bg-[#f3faf5] p-5"><p className="font-semibold text-slate-950">{label}</p><p className="mt-3 text-3xl font-bold tabular-nums text-[#15533d]">{formatRate(rate)}<span className="ml-2 text-sm font-medium text-slate-500">/måned</span></p></article>; }
function SourceLine({ href, label }: { href: string; label: string }) { return <p className="text-xs leading-5 text-slate-500">Kilde: <a className="font-semibold text-[#15533d] hover:underline" href={href}>{label} ↗</a></p>; }
function DataTable({ headers, minWidth = "620px", rows }: { headers: string[]; minWidth?: string; rows: ReactNode[][] }) { return <div className="overflow-x-auto rounded-[5px] border border-black/10 bg-white"><table className="w-full border-collapse text-left" style={{ minWidth }}><thead className="bg-[#f1f7f2] text-sm text-slate-700"><tr>{headers.map((header) => <th className="px-4 py-3 font-semibold" key={header}>{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-200 text-sm text-slate-800">{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td className="px-4 py-3.5" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }

function formatDate(value: string) { return new Intl.DateTimeFormat("nb-NO", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }

function formatShortDate(value: string) { return new Intl.DateTimeFormat("nb-NO", { day: "2-digit", month: "2-digit", year: "numeric", timeZone: "UTC" }).format(new Date(value + "T00:00:00Z")); }
